before_cache:
  - sudo chown -R travis:travis $HOME/.m2
  # Ensure that jobs do not influence each other with installed Neo4j Spark Connector Jars
  - rm -rf $HOME/.m2/repository/org/neo4j-contrib/neo4j-spark-connector/

cache:
  apt: true
  directories:
    - ${HOME}/.m2
jobs:
  include:
    - name: "Test for Spark 2.4 and Scala 2.11"
      jdk: "openjdk8"
      language: scala
      scala:
        - 2.11.12
      dist: trusty
      install:
        - ./mvnw clean install -D skipTests -P scala-2.11 -P spark-2.4 --no-transfer-progress
      script:
        - echo '*** Executing tests with Spark 2.4, Scala 2.11 and Neo4j 3.5'
        - ./mvnw verify -P neo4j-3.5
        - echo '*** Executing tests with Spark 2.4, Scala 2.11 and Neo4j 4.0'
        - ./mvnw verify -P neo4j-4.0 --no-transfer-progress
        - echo '*** Executing tests with Spark 2.4, Scala 2.11 and Neo4j 4.1'
        - ./mvnw verify -P neo4j-4.1 --no-transfer-progress
        - echo '*** Executing tests with Spark 2.4, Scala 2.11 and Neo4j 4.2'
        - ./mvnw verify -P neo4j-4.2 --no-transfer-progress
    - name: "Test for Spark 2.4 and Scala 2.12"
      jdk: "openjdk8"
      language: scala
      scala:
        - 2.12.13
      dist: trusty
      install:
        - ./mvnw clean install -D skipTests -P scala-2.12 -P spark-2.4 --no-transfer-progress
      script:
        - echo '*** Executing tests with Spark 2.4, Scala 2.12 and Neo4j 3.5'
        - ./mvnw verify -P neo4j-3.5
        - echo '*** Executing tests with Spark 2.4, Scala 2.12 and Neo4j 4.0'
        - ./mvnw verify -P neo4j-4.0 --no-transfer-progress
        - echo '*** Executing tests with Spark 2.4, Scala 2.12 and Neo4j 4.1'
        - ./mvnw verify -P neo4j-4.1 --no-transfer-progress
        - echo '*** Executing tests with Spark 2.4, Scala 2.12 and Neo4j 4.2'
        - ./mvnw verify -P neo4j-4.2 --no-transfer-progress
    - name: "Test for Spark 3.0 and Scala 2.12"
      jdk: "openjdk8"
      dist: trusty
      language: scala
      scala:
        - 2.12.13
      install:
        - ./mvnw clean install -D skipTests -P spark-3.0 --no-transfer-progress
      script:
        - echo '*** Executing tests with Spark 3.0, Scala 2.12 and Neo4j 3.5'
        - ./mvnw verify -P neo4j-3.5
        - echo '*** Executing tests with Spark 3.0, Scala 2.12 and Neo4j 4.0'
        - ./mvnw verify -P neo4j-4.0 --no-transfer-progress
        - echo '*** Executing tests with Spark 3.0, Scala 2.12 and Neo4j 4.1'
        - ./mvnw verify -P neo4j-4.1 --no-transfer-progress
        - echo '*** Executing tests with Spark 3.0, Scala 2.12 and Neo4j 4.2'
        - ./mvnw verify -P neo4j-4.2 --no-transfer-progress
# dfantuzzi: Spark package for Scala 2.13 is not yet published on maven https://mvnrepository.com/artifact/org.apache.spark/spark-core
#    - name: "Test for Scala 2.13"
#      jdk: "openjdk8"
#      dist: trusty
#      language: scala
#      scala:
#        - 2.13.4
#      install:
#        - ./mvnw clean install -D skipTests -P scala-2.13 --no-transfer-progress
#      script:
#        - echo '*** Executing tests with Scala 2.13 and Neo4j 3.5'
#        - ./mvnw verify -P neo4j-3.5
#        - echo '*** Executing tests with Scala 2.13 and Neo4j 4.0'
#        - ./mvnw verify -P neo4j-4.0 --no-transfer-progress
#        - echo '*** Executing tests with Scala 2.13 and Neo4j 4.1'
#        - ./mvnw verify -P neo4j-4.1 --no-transfer-progress
#        - echo '*** Executing tests with Scala 2.13 and Neo4j 4.2'
#        - ./mvnw verify -P neo4j-4.2 --no-transfer-progress