
= Quick Start

== Neo4j Spark Connector Plugin

=== Overview

Neo4j Spark Connector allows Spark to read from and write to Neo4j databases.

=== Getting Started

Reading all the nodes of type `Person` from your local Neo4j instance is as simple as this:

```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
        .option("url", "bolt://localhost:7687")
        .option("labels", "Person")
        .load()
        .show()
```

The above code will produce something similar to this:

```
+----+--------+----+---+
|<id>|<labels>|name|age|
+----+--------+----+---+
|   0|[Person]|John| 32|
+----+--------+----+---+
```

=== Neo4j Options

Spark method `option` is used to configure the Neo4j Connector.

```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
        .option("url", "bolt://localhost:7687")
        .option("authentication.type", "basic")
        .option("authentication.basic.username", "myuser")
        .option("authentication.basic.password", "neo4jpassword")
        .option("labels", "Person")
        .load()
```

.List of available options
|===
|Setting Name |Description |Default Value |Required 

4+|*Driver Options*

|`url`
|The url of the Neo4j instance to connect to
|_(none)_
|Yes

|`authentication.type`
|The authentication method to be used: `none`, `basic`, `kerberos`, `custom`. More info https://neo4j.com/docs/driver-manual/4.1/client-applications/#driver-authentication[here]
|`basic`
|No

|`authentication.basic.username`
|Username to use for basic authentication type
|_(none)_
|No

|`authentication.basic.password`
|Username to use for basic authentication type
|_(none)_
|No

|`authentication.kerberos.ticket`
|Kerberos Auth Ticket
|_(none)_
|No

|`authentication.custom.principal`
|This used to identify who this token represents
|_(none)_
|No

|`authentication.custom.credentials`
|This are the credentials authenticating the principal
|_(none)_
|No

|`authentication.custom.realm`
|This is the "realm:" string, specifying the authentication provider
|_(none)_
|No

|`encryption.enabled`
|Specify if encryption should be enabled. This setting is totally ignored if you use a URI scheme with +s or +ssc
|`false`
|No

|`encryption.trust.strategy`
|Set certificate trust strategy, is ignored in case the connection URI uses `+s` or `+ssc` as suffix.
|`TRUST_SYSTEM_CA_SIGNED_CERTIFICATES`
|No

|`encryption.ca.certificate.path`
|Set certificate path for `TRUST_CUSTOM_CA_SIGNED_CERTIFICATES` trust strategy
|_(Neo4j Driver default)_
|No

|`connection.max.lifetime.msecs`
|Connection lifetime in milliseconds
|_(Neo4j Driver default)_
|No

|`connection.liveness.timeout.msec`
|Liveness check timeout
|_(Neo4j Driver default)_
|No

|`connection.acquisition.timeout.msecs`
|Connection acquisition timeout in milliseconds
|_(Neo4j Driver default)_
|No

|`connection.timeout.msecs`
|Connection timeout in milliseconds
|_(Neo4j Driver default)_
|No

4+|*Session Options*

|`database`
|Database name to connect to. As the driver allows to define the database in the URL,
in case you set this option will have the priority compared to the one defined in the URL
|``
|No

|`access.mode`
|Possible values are: `read`, `write`.
Used only while you're pulling data from Neo4j.
In case of `read` the connector, in a cluster environment,
will route the requests to the followers, otherwise to the leader.
|`read`
|No

4+|*Data Read Options*

|`query`
|Specify a query to read the data
|_(none)_
|Yes^*^

|`labels`
|List of labels separated by `:`. First label is the primary label
|_(none)_
|Yes^*^

|`relationship`
|Name of a relationship
|_(none)_
|Yes^*^

|`relationship.nodes.map`
|If true return `source` and `target` nodes as Map<String, String>, otherwise we flatten the properties by returning
every single node property as column prefixed by `source` or `target`
|`true`
|No

|`relationship.source.labels`
|List of source node Labels separated by `:`
|``
|Yes^*^

|`relationship.target.labels`
|List of target node Labels separated by `:`
|``
|Yes^*^

|`schema.flatten.limit`
|Number of records to be used to create the Schema (only if APOC are not installed)
|`10`
|No

|`schema.strategy`
|Strategy used by the connector in order to compute the Schema definition for the Dataset. Values `string` and
`sample`. If `string` coerces all the properties to String otherwise it will try to sample the Neo4j's dataset.
|`sample`
|No

|`pushdown.filters.enabled`
|Enable or disable the Push Down Filters support
|`true`
|No

4+|*Data Write Options*

|`batch.size`
|Number of records to be passed to the transaction
|`5000`
|No

|`relationship.save.strategy`
|<<quickstart_writer.adoc#node-keys,Docs here>>
|``
|Yes for <<quickstart_writer.adoc#keys-strategy,KEYS>> strategy

|`relationship.source.labels`
|List of source node Labels separated by `:`
|``
|Yes^*^

|`relationship.source.node.keys`
|<<quickstart_writer.adoc#node-keys,Docs here>>
|``
|No

|`relationship.source.save.mode`
|<<quickstart_writer.adoc#node-save-modes,Node Save Mode>>
|`Match`
|No

|`relationship.source.node.props`
|<<quickstart_writer.adoc#node-keys,Docs here>>
|``
|No

|`relationship.target.labels`
|List of target node Labels separated by `:`
|``
|Yes^*^

|`relationship.target.node.keys`
|<<quickstart_writer.adoc#node-keys,Docs here>>
|``
|No

|`relationship.target.save.mode`
|<<quickstart_writer.adoc#node-save-modes,Node Save Mode>>
|`Match`
|No

|`relationship.target.node.props`
|<<quickstart_writer.adoc#node-keys,Docs here>>
|``
|No

|===

^*^ Just one of the options can be specified.

== Read Data

Reading data from a Neo4j Database can be done in 3 ways:

 * with a Cypher query
 * with a set of node Labels 
 * by specifying a relationship

=== Consideration on the schema

Spark works with data in a tabular fixed schema. To accomplish this Neo4j Connector has a schema infer system that creates the schema based on the data requested for the read. Each read data method has is own strategy to create it, that will be explained it each section.

TK list of supported data types

=== Consideration on the filters

The Neo4j Spark Connector implements the `SupportPushDownFilters` interface, that allows you to push the Spark filters down to the Neo4j layer. In this way the data that Spark will receive will be already filtered by Neo4j.

You can manually disable the Push Down Filters support using the `pushdown.filters.enabled` option and set it to `false` (default is `true`).

If you use use the filter function more than once, like in this example:
```scala
df.where("name = 'John Doe'").where("age = 32")
```
The conditions will be automatically joined with an `AND` operator.

[NOTE]
When using `relationship.node.map = true` or `query` the PushDownFilters support is not active, thus the filters will be applied by Spark and not by Neo4j.

==== How we extract the schema

As Neo4j has a schema-less approach and Spark needs a Schema in order to create a Dataset,
we use several approaches in order to sample the dataset into Neo4j and compute the schema for Spark's Dataset.

===== Extract schema for Nodes

In case you're extracting nodes from Neo4j we try as first step to invoke the `apoc.meta.nodeTypeProperties` procedure,
in case the procedure is not installed we'll execute the following Cypher query:

```cypher
MATCH (n:<labels>)
RETURN n
ORDER BY rand()
LIMIT <limit>
```

Where `<labels>` is the list of labels provided via `.option("labels", ":MyLabel:MyOtherLabel")` and `<limit>` is the
value provided via `.option("schema.flatten.limit", "100")`

===== Extract schema for Relationships

In case you're extracting a relationship from Neo4j we try as first step to invoke the `apoc.meta.relTypeProperties` procedure,
in case the procedure is not installed we'll execute the following Cypher query:

```cypher
MATCH (source:<source_labels>)-[rel:<relationship>]->(target:<target_labels>)
RETURN rel
ORDER BY rand()
LIMIT <limit>
```

Where:

 * `<source_labels>` is the list of labels provided via `.option("relationship.source.labels", ":MyLabel:MyOtherLabel")`
 * `<target_labels>` is the list of labels provided via `.option("relationship.target.labels", ":MyLabel:MyOtherLabel")`
 * `<relationship>` is the list of labels provided via `.option("relationship", "MY_RELATIONSHIP")`
 * `<limit>` is the value provided via `.option("schema.flatten.limit", "100")`

==== Complex Data Types

Spark doesn't support all Neo4j data types (ie: Point, Time, Duration). Such types are transformed into Struct types containing all the useful data.

|===

|Type |Struct 

|`Duration`
a|
----
Struct(Array(
    ("type", DataTypes.StringType, false),
    ("months", DataTypes.LongType, false),
    ("days", DataTypes.LongType, false),
    ("seconds", DataTypes.LongType, false),
    ("nanoseconds", DataTypes.IntegerType, false),
    ("value", DataTypes.StringType, false)
  ))
----

|`Point`
a|
----
Struct(Array(
    ("type", DataTypes.StringType, false),
    ("srid", DataTypes.IntegerType, false),
    ("x", DataTypes.DoubleType, false),
    ("y", DataTypes.DoubleType, false),
    ("z", DataTypes.DoubleType, true),
  ))
----

|`Time`
a|
----
Struct(Array(
    ("type", DataTypes.StringType, false),
    ("value", DataTypes.StringType, false)
  ))
----

|=== 

=== Read data by Node Labels

You can both specify a single label, like this example
```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
        .option("url", "bolt://localhost:7687")
        .option("labels", "Person")
        .load()

df.show()
```

Multiple labels can be specified, separated by `:`
```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
        .option("url", "bolt://localhost:7687")
        .option("labels", "Person:Customer:Admin")
        .load()

df.show()
```

When reading data with this method, the Dataframe will contain all the fields contained in the nodes, plus 2 additional columns.

 * `<id>` the internal Neo4j id
 * `<labels>` a list of labels for that node

==== Schema

If APOC are available, the schema will be created with `apoc.meta.nodeTypeProperties`.
Otherwise the first 10 (or any number specified by the `schema.flatten.limit` option) results will be flattened and the schema will be create from those properties.

===== Example

```
CREATE (p1:Person {age: 31, name: 'Jane Doe'}),
    (p2:Person {name: 'John Doe', age: 33, location: null}),
    (p3:Person {age: 25, location: point({latitude: -37.659560, longitude: -68.178060})})
```

Will create this schema

|===
|Field |Type 

|<id>|Int

|<labels>|String[]

|age|Int

|name|String

|location|Point

|===

=== Read data by Relationship Type

You can specify a Cypher Path in this way:
```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
        .option("url", "bolt://localhost:7687")
        .option("relationship", "BOUGHT")
        .option("relationship.source.labels", "Person")
        .option("relationship.target.labels", "Product")
        .load()

df.show()
```

This will create a Cypher Query as it follows:

```cypher
MATCH (source:Person)-[rel:BOUGHT]->(target:Product)
RETURN source, rel, target
```

When reading data with this method, the Dataframe will contain all the fields contained in the relationship, plus:

* `<id>` the internal Neo4j id
* `<relationshipType>` the relationship type

and depending on the value of `relationship.node.map` option, if `true`:

* `source` the Map<String, String> of source node
* `target` the Map<String, String> of target node

otherwise, if `false`:

[[bookmark-rel-read-schema]]
* `<sourceId>` the internal Neo4j id of source node
* `<sourceLabels>` a list of labels for source node
* `<targetId>` the internal Neo4j id of target node
* `<targetLabels>` a list of labels for target node
* `source.[property name]` source node property
* `target.[property name]` target node property
* `rel.[property name]` relationship property

==== Filter

You can use Spark to filter properties of the relationship, the source node, or the target node. Just use the correct prefix:

If `relationship.node.map` is set to **false**

* ``\`source.[property]` `` for the source node properties
* ``\`rel.[property]` `` for the relation property
* ``\`target.[property]` `` for the target node property

If `relationship.node.map` is set to **true**

* ``\`<source>`.\`[property]` `` for the source node map properties
* ``\`<rel>`.\`[property]` `` for the relation map property
* ``\`<target>`.\`[property]` `` for the target node map property

in this case, all the map values will be strings, so the filter value must be a string too.

```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
      .option("relationship.node.map", false)
      .option("relationship", "BOUGHT")
      .option("relationship.source.labels", "Person")
      .option("relationship.target.labels", "Product")
      .load()

df.where("source.name = 'John Doe' AND target.price >= 33")
```

==== Schema

If APOC are available, the schema will be created with `apoc.meta.relTypeProperties`.
Otherwise the first 10 (or any number specified by the `schema.flatten.limit` option) results will be flattened and the schema will be create from those properties.

=== Read data by custom Cypher Query

You can specify a Cypher query in this way:
```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
      .option("query", "MATCH (n:Person) WITH n LIMIT 2 RETURN collect(n) AS nodes")
      .load()

df.show()
```

[NOTE]
We recommend that individual property fields be returned, rather than returning  graph entity (node, relationship, and path) types.
This best maps to Spark's type system and yields best results.
So instead writing this `MATCH (p:Person) RETURN p` please write this: `MATCH (p:Person) RETURN id(p) as id, p.name as name`.
If your query returns a graph entity please use the `labels` or `relationship`.

The struct of the Dataset returned by the query is influenced by the query itself, in this particular context it could happen
that the connector could not be able to sample the Schema from the query, in these particular cases we suggest trying with
the option `schema.strategy` defined as `string` as it follows:

```scala
val df = spark.read.format("org.neo4j.spark.DataSource")
      .option("query", "MATCH (n:Person) WITH n LIMIT 2 RETURN collect(n) AS nodes")
      .option("schema.strategy", "string")
      .load()

df.show()
```

This means that the struct returned by the query will be composed by strings that you can than cast via simply Spark's
transformations.

[NOTE]
Inference (`schema.strategy` = `sample`) is good when all instances of a property in neo4j are the same type,
and string followed by cast is better when property types may differ.
Remember that Neo4j does not enforce property typing, and so `person.age` could sometimes be a `long
and sometimes be a `string`.

==== Schema

The first 10 (or any number specified by the `schema.flatten.limit` option) results will be flattened and the schema will be created from those properties.